import { User } from "./model/User";
export { User } from "./model/User";
export declare function getUser(): User;
export declare function getUserProducts(): Array<string>;
export declare function isUserLoggedIn(): boolean;
export declare function isUpdateForced(): boolean;
export declare function isUserSessionExpired(): boolean;
export declare function hasCookie(cookiename: string): boolean;
export declare function getCookieValue(cookiename: string): string;
export declare function getFeatureLoggingState(): string;
